config/routes.rb
Habriki::Application.routes.draw do

  constraints :format => 'json' do
    namespace 'api' do
      namespace 'community', :path => nil, :module => nil do
        scope 'communities/:community_id' do
          scope :module => 'communities' do
            resources :members, :only => [] do
              scope :module => 'members' do
                resources :ratings, :only => [:create]
              end
            end
            resources :posts, :only => [] do
              scope :module => 'posts' do
                resources :ratings, :only => [:create]
                resources :comments, :only => [:create]
              end
            end
            scope :module => 'posts' do
              resources :comments, :only => [] do
                scope :module => 'comments' do
                  resources :ratings, :only => [:create]
                end
              end
            end
          end
        end
      end
    end
  end

  namespace 'm', :module => 'mobile' do
    resources :communities, :only => [:show] do
      resources :posts, :only => [:show]
    end
  end

  namespace 'feeds' do
    scope :module => 'communities' do
      resources :posts, :only => [:index]
    end
  end

  scope :module => 'web' do
    constraints(SubdomainConstraint) do
      namespace 'community', :path => nil, :module => nil do
        root :to => 'communities/home#index'
        scope :module => 'communities' do
          scope :path => 'd' do
            devise_for :members, :class_name => 'Community::Member'
            namespace 'member', :path => 'members', :module => nil do
              resource :confirmation, :only => [:show]
            end
          end
          resources :members, :only => [:index]
          scope :module => 'members' do
            resources :members, :only => [:show, :edit, :update] do
              resources :comments, :only => [:index]
              resources :posts
            end
          end
          resources :blogs, :only => [:index, :show] do
            scope :module => 'blogs' do
              resources :posts, :only => [:index, :show]
            end
          end
          resources :posts, :only => [] do
            collection do
              get :recent
            end
          end
          resources :tags, :only => [:show]
          resource :search, :only => [:show]
          namespace 'admin' do
            root :to => 'home#index'
            resources :blogs
          end
        end
      end
    end

    root :to => 'home#index'

    namespace 'account' do
      resource :user
      resources :communities
    end

    scope :path => 'd' do
      devise_for :users
    end
    resources :users, :only => [:edit, :update]
  end

end

app/views/web/shared/_blog_posts.html.haml
- if blog_posts.any?
  - blog_posts.each do |post|
    %h2 #{link_to post, community_blog_post_path(post.blog, post)}
    %div= truncate post.body, :length => 500

app/views/web/shared/_blogs.html.haml
- if blogs.any?
  - blogs.each do |blog|
    %h2 #{link_to blog, community_blog_posts_path(blog)}

app/views/web/shared/_posts.html.haml
- if posts.any?
  - posts.each do |post|
    %h3.inline-block #{link_to post.blog, community_blog_posts_path(post.blog)} - #{link_to_if post.active?, post, community_blog_post_path(post.blog, post)}
    - if post.member == current_community_member
      %span= link_to 'edit', edit_community_member_post_path(post.member, post) 
    %div= truncate post.body, :length => 500
    %div
      - post.tags.each do |tag|
        = link_to tag, community_tag_path(tag)